### ISSUE TITLE
Locos filtern für Depot-Koordinatoren

### ISSUE THREAD

**Issue by oliverganz** [ortoloco/ortoloco#10]
Die politolocos können sich anmelden und haben dann Zugriff auf das Adminrecht "politoloco versenden". Was ähnliches braucht es für die Depot-KoordinatorInnen: Die sollten nur die Adminrechte "Depotliste drucken" und "Locos filtern" haben. Das gilt für folgende user:

siehe mail

**Comment by olmaga** [comment]
Antworten auf emails sollten auch wieder an die Sender zurück (also die Depot-Koordinatoren, nicht info@)

**Comment by amerkle** [comment]
Branche gemerged. @oliverganz : kannst du das noch deployen?

**Comment by olmaga** [comment]
Adrian, ich han einigi Kommentär inegschriebe, grundsätzlich chöntimes aber
eigentli release.

Leider het de Robert de Master komplett kabutt gmacht und mer müend am
nögste ITloco-Abig mal nomol ufruume

Am 20. Januar 2015 um 22:10 schrieb amerkle <notifications@github.com>:

> Branche gemerged. @oliverganz <https://github.com/oliverganz> : kannst du
> das noch deployen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ortoloco/ortoloco/issues/10#issuecomment-70734031>.
>



-- 
----------------------------------
http://about.me/olmaga
<http://gladdress.com/3aedb798-4ba7-0c27-29e2-fac3c4c86103.html>
