### ISSUE TITLE
Mailinglisten

### ISSUE THREAD

**Issue by Lea-ortoloco** [ortoloco/ortoloco#16]
Z.B. abpacken@ortoloco.ch, automatisch aus Datenbank generiert (alle, die im Tätigkeitsbereich Abpacken eingetragen sind). Alle, die auf der Mailingliste sind, können an die Adresse antworten und die Mail geht an alle raus. Sich selber austragen nicht möglich! Nur austragen von Tätigkeitsberich möglich. Falls es ausartet, Selber-Antworten-Funktion sperren.

**Comment by tinaortoloco** [comment]
Die BereichskoordinatorInnen möchten gern das Issue #17 umgesetzt haben, das Issue #16 braucht es nicht. Im Issue #17 braucht es aber das Kontaktfeld nicht.

**Comment by olmaga** [comment]
bin ich dagegen => muss mind. noch einmal gefragt werden... wir haben ja jetzt mal kommunikation 1.0 erledigt
