### ISSUE TITLE
Kommunikation unter den Gnossis vereinfachen

### ISSUE THREAD

**Issue by Lea-ortoloco** [ortoloco/ortoloco#17]
Funktion: Wenn man einen Tätigkeitsbereich auswählt, anklicken: Bist du damit einverstanden, dass deine Mailadresse und Tel.nr. an die Leute vom Tätigkeitsbereich weitergegeben wird für die interne Kommunikation? Wenn ja, kann man ein pdf rauslassen mit dem Namen, Mailadresse, Tel.nr. 
Oder: Man kann alle Namen des TB's sehen und dann an einzelne Person Mail schicken ohne deren Emailadresse zu sehen, so eine Art Kontaktfeld. Absender ist dann die eigene Mailadresse.
Idee: Die Leute können direkt untereinander kommunzieren, z.B. wenn sie einen Ersatz suchen wollen für einen Einsatz.

**Comment by tinaortoloco** [comment]
Mit diesem Issue könnt ihr mal noch warten, Ursina wird das noch mit den BereichskoordinatorInnen anschauen.

**Comment by tinaortoloco** [comment]
Die BereichskoordinatorInnen möchten gern das Issue #17 umgesetzt haben, das Issue #16 braucht es nicht. Im Issue #17 braucht es aber das Kontaktfeld nicht.

**Comment by olmaga** [comment]
bin ich dagegen => muss mind. noch einmal gefragt werden... wir haben ja jetzt mal kommunikation 1.0 erledigt
