### ISSUE TITLE
Kinder und Mitarbeit

### ISSUE THREAD

**Issue by Lea-ortoloco** [ortoloco/ortoloco#18]
Bei Arbeitseinsätzen eintragen können, wieviele Kinder mitkommen (geben keine Böhnli), diese sollen auch angezeigt werden, z.B. Lea Egloff + 2 Kinder, das ermöglicht den Eltern zu sehen, ob noch andere Kinder kommen und für die Orga ist es auch besser.

**Comment by tinaortoloco** [comment]
Dieses Issue kann mal noch warten, die BG diskutiert gern nochmal über diese zwei Möglichkeiten (Kinder als fixer Eintrag oder Infofenster). Ihr hört dann von uns.

**Comment by tinaortoloco** [comment]
Das wird eventuell wieder aktuell, da eine Konferenz zum Thema Kinder und ortoloco geplant ist. Als ein Resultat oder Umsetzungswunsch könnte genau dieses Thema wieder aufkommen. Also ist es gut, wenn wir das im Hinterkopf behalten.
