### ISSUE TITLE
admin-Jobs

### ISSUE THREAD

**Issue by Lea-ortoloco** [ortoloco/ortoloco#21]
Im Adminbereich ortoloco.ch/admin würd ich gerne was anpassen bei den Jobs: Die alten (Datum vorbei) und die noch kommenden sollten irgendwie separat darstellbar sein. Sonst verliert man sich in den unzähligen Jobs, wenn man z.B. bei einem Ernteeinsatz was ändern will und 50 in der Liste angezeigt werden und ich das richtige Datum finden will.

**Comment by tinaortoloco** [comment]
Wurde nie diskutiert, daher würde ich das mal closen.
