### ISSUE TITLE
Kommunikation mit Warteliste

### ISSUE THREAD

**Issue by Lea-ortoloco** [ortoloco/ortoloco#22]
Die Leute auf der Warteliste sollten nicht automatisch alle Mails kriegen. Aktuell kriegen sie glaub's alle Infos wie normale Gemüseabonnenten. Es sollte die Möglichkeit geben, die Mails nur an Leute zu schicken, welche real ein Abo besitzen oder einem angeschlossen sind (also aktive Abos). Ein ähnliches Problem besteht mit den Leuten, die einen Anteilschein bestellt, aber noch nicht bezahlt haben. Das können wir aber erst nach der Aktualisierung der Anteilschein-History lösen, aktuell gibt es ja kaum reale AS-Besitzer auf my.ortoloco.

**Comment by tinaortoloco** [comment]
http://my.ortoloco.ch/my/mails
Hier sollten beim Anwählen von "alle AbonnentInnen" nur die aktiven AbonnentInnen angeschrieben werden. Super, wenn ihr das mal noch so einrichten könnt. Ich nehme die Priorität mal raus und setze sie wieder höher, sobald wir wieder eine Warteliste haben. Schön, wenn ihr es vorher machen könnt.
