### ISSUE TITLE
Wiki Integration

### ISSUE THREAD

**Issue by amerkle** [ortoloco/ortoloco#29]
Es existieren mindestens zwei Wikis, die extern gehostet werden.
http://politoloco.wikispaces.com/
http://fungiloco.wikispaces.com/

Einerseits wäre es schön, diese Wikis auch auf unserem eigenen Server zu haben, andererseits hat wikispaces angekündigt, dass es künftig keine Gratis wikis mehr geben wird. 

Vielleicht wäre django-wiki eine Option: https://github.com/django-wiki/django-wiki

**Comment by tinaortoloco** [comment]
Dieses Issue hat keine Priorität. Löscht es nicht ganz, aber macht zuerst alles andere wichtige. :-)
