### ISSUE TITLE
Mailkommunikation BG & Bereichskoordination: Umstellung von horde auf xiala vornehmen

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#30]
Lieber Oli

Lea hat sich nun endgültig aus dem Staub gemacht - jetzt versuche ich mich als Issuerin und Sprachrohr von der BG. Sie hat mir gesagt, dass du diese Übertragung von horde auf xiala bereits angedacht hast - was braucht es noch, damit du rsp. ihr das machen könnt?
Es wäre gut, wenn das bald mal passiert, horde spinnt total (BG-Verteiler ist zum 4. Mal kaputt) und Lot ist nicht mehr wirklich bei ortoloco dabei.

Danke fürs Feedback, liebe Grüsse
Tina

**Comment by olmaga** [comment]
mer bliibed uf horde
