### ISSUE TITLE
Als Buchhalter, soll ich jeden Dienstag die aktuellen Depotlisten per E-Mail bekommen, so dass ich sie in Excel bearbeiten kann.

### ISSUE THREAD

**Issue by rbf** [ortoloco/ortoloco#33]
Ich habe grade mit Tex gesprochen, weil er wissen wollte, ob die Geschichte der Depotlisten verfügbar ist. Für die Buchhaltung, soll er nachvollziehen können, wann welche Locos in welchem Depot angemeldet waren.

Eine Lösung ist, automatisch jeden Dienstag (Tag von Tex vorgeschlagen) die Depotlisten zu generieren und ihm per E-Mail schicken. PDF ginge, aber CSV wäre viel besser, weil er dann die Info auf Excel bearbeiten soll. Eventuell könnte man sie noch dazu im Adminbereich speichern. Dass sollte am Besten ab Januar 2015 geschehen.

Wenn diese Info für das aktuelle Jahr (2014) noch herauszufinden ist, sollen wir das am kommenden Donnerstag Tex schicken.

**Comment by olmaga** [comment]
Am besten:
Für jeden Ortoloco gibts eine Zeile:
Name:    1. 2. 3. 4. 5.
Oliver         X  X X

Das heisst: oli hatte von woche 2-4 ein abo.

Achtung: Das brauchts für alle zusatzabos auch...

**Comment by motu55** [comment]
nicht mehr aktiell siehe #102
