### ISSUE TITLE
Als Admin sollte ich einmalige Jobs ausschreiben können

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#45]
Als Admin ist es praktisch, wenn man einmalige Jobs ausschreiben könnte, ohne dass eine eigene Jobart erstellt werden muss. Wenn für alle Jobs eine Jobart erstellt werden muss (auch wenn sie nur einmal stattfinden), wird es dort unübersichtlich.

**Comment by olmaga** [comment]
machen wir im moment nicht - ist nicht realistisch umsetzbar
