### ISSUE TITLE
Tätigkeitsbereich-chefs müssen emails an nur ihre tbs schicken können

### ISSUE THREAD

**Issue by oliverganz** [ortoloco/ortoloco#5]

**Comment by tinaortoloco** [comment]
http://my.ortoloco.ch/my/filters
Dieses Issue muss etwas angepasst werden: Es geht vor allem darum, dass die TBs ihre Bereiche filtern und die Mailadressen kopieren können, damit sie von ihren privaten Mailaccounts Mails verschicken können. Diese Funktion gab es schonmal, ist aber verschwunden.

**Comment by tinaortoloco** [comment]
Dieses Issue können wir mal schliessen, es entspricht nicht mehr den Bedürfnissen.

**Comment by olmaga** [comment]
this works
