### ISSUE TITLE
Gemüsedepot Wegbeschreibung fehlt

### ISSUE THREAD

**Issue by mklarmann** [ortoloco/ortoloco#50]
Bei den Depots bräuchte man einen kurzen text, um genau zu beschreiben wo die Gemüsetüte zu finden ist. Schön wäre es wenn man die Seite mit den Infos ausdrucken kann.

**Comment by schlangen** [comment]
Aktuell noch in Klärung: ggf. bereits durch Informationsmail an Neu-AbonnentInnen gelöst (gem. Info Betriebsgruppe).

**Comment by motu55** [comment]
Das feld selber ist da https://github.com/ortoloco/ortoloco/issues/89 behandelt die datenabfüllung
