### ISSUE TITLE
UX für Jobs signup - ITloco

### ISSUE THREAD

**Issue by mklarmann** [ortoloco/ortoloco#51]
Änderung eines Termins, wird den Teilnehmern nicht mitgeteilt.

Betrifft JOB Beschreibung??:
Email nach Anmeldung fehlen relevante Informationen ( Adresse + Wegbeschreibung, Email Tina - Anstatt Veranstaltungs Organisator, Eventuell Telefonnummer - falls man sich verirrt)

**Comment by rbf** [comment]
Da scheinen mehrere Erweiterungen angesprochen zu sein.
Könntest du sie bitte genauer auflisten und beschreiben?
Danke!

**Comment by motu55** [comment]
neues email wenn zeit ändert, auch wird ein kontakt angegeben de bereichverantwortlichen und im bereich kann auch definiert werden ob telnr oder nur email angeben wird
