### ISSUE TITLE
Beim Registrieren OHNE Abo wird  doch ein kleines Abo angelegt.

### ISSUE THREAD

**Issue by SachaSchlegel** [ortoloco/ortoloco#52]
Beim registrieren OHNE Abo wird dennoch ein kleines Abo angelegt.

Das ist aufgefallen als wir, die Gartenkooperative Region Liechtenstein-Werdenberg, uns offiziell bei Ortoloco (auf my.ortolocolo.ch) registriert haben und soeben beim Anpassen der Software für uns.

Irgendwo im code von  my_ortoloco => views.py => def my_createabo(request):

**Comment by tinaortoloco** [comment]
Lieber Sacha

Danke für den Hinweis.
Werde es den ITs weiterleiten.

Liebe Grüsse
Tina


Zitat von Sacha Schlegel <notifications@github.com>:
