### ISSUE TITLE
Als Admin die Möglichkeit haben, die Mailadressen per Excel-Export-Button zu exportieren

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#57]
Änderungswunsch von Andreas Geiger:
Insbesondere um das Debitorenmanagement zu erleichtern wünschen wir uns für die Mailadressliste im Admin-Bereich von my.ortoloco einen Excel-Export-Button. 
Falls das nicht möglich sein sollte, wäre auch die Möglichkeit praktisch, alle Adressen auf einer einzigen Seite im Browser anzeigen zu lassen.
Hintergrund: Derzeit sind die Mailadressen auf 7 Seiten verstreut (oder man sucht sie alle einzeln von Hand). Um den manuellen Aufwand beim Zusammensuchen der Mailadressen von säumigen Abonnenten zu reduzieren, benötigen wir uns diese Funktion.
Bei Listen in web-basierten Tools befindet sich der Excel-Export-Button meist oben rechts.

**Comment by mklarmann** [comment]
Hallo Tina / Andreas

Man kann bereits als Admin auf der Webseite alle Emailadressen auf einer Seite anzeigen:
http://ortoloco.ch/my/filters

Mit Copy&Paste auch in eine Excel Tabelle übernehmen.
Erfüllt das bereits eure Anforderung?

lg Manuel

**Comment by motu55** [comment]
hallo

Es gibt nun die genrelle Möglichkait alle Loscos in einem Excell zu exportieren. 
@tinaortoloco reicht das so oder war die idee das filter resultat als excel zu exportieren?

**Comment by tinaortoloco** [comment]
Am besten schauen wir uns das mal an, ich kann mir darunter grad noch nichts vorstellen.
Aber höchstwahrscheinlich erfüllt das die Anforderungen. Danke!!
