### ISSUE TITLE
Als Admin: Beim Mails verschicken verschiedene Optionen auswählen können, an welche Adresse die Antwort geht

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#58]
Mit Thomas haben wir am letzten IT-Loco-Treff nach einer Lösung gesucht, wie die Verantwortlichen für die TBs (Tätigkeitsbereiche) mit den Leuten in ihrer Gruppe kommunizieren können. Wunsch: Auswahl der Adressen über die Filterfunktion von my.ortoloco, Mails verschicken mit der Mailfunktion "Mail verschicken an diese Adressen", Auswahl an welche Adresse die Antwort der angeschriebenen Leute kommt (Umleitung auf die private Mailadressen der TB-Verantwortlichen).
Danke Thomas, dass du hier noch ergänzt, wie das genau gemacht werden kann.

**Comment by fathoma** [comment]
Im Moment werden bei der Mailfunktion Emails immer von info@ortoloco versendet. Das Hauptproblem dabei ist, dass Antworten auf diese Emails die Verantwortlichen der TBs nicht direkt erreichen sondern zT zuerst manuell weitergeleitet werden müssen.

Deshalb werden die Adressen im Moment entweder von der Webseite wegkopiert und Emails direkt von der privaten Aresse verschickt (mühsam und Adressen werden dann uU wegen Spamverdacht blockiert) oder mit dem Vermerk "Antwort bitte nicht an info@ sondern an bla@" verschickt.

Als Lösungen haben wir besprochen:

1) Als Absender der Emails wird von der Webseite die private Email Adresse statt info@ benutzt. Sehr problematisch bzw unmöglich wegen Spamschutz.
2) Emails werden weiterhin von info@ versendet aber mit reply-to, so dass Antworten an die private Email Adresse gehen.
3) Es werden neue Email Adressen für die TBs erstellt und als Absender verwendet, welche dann je nach Wunsch entweder Weiterleitungen auf die private Email Adresse sind oder normale Email Accounts mit Webmail.
 
Wir haben uns für Lösung 3) entschieden unter anderem auch weil info@ in Zukunft wenn möglich nur noch für "offizielle" Ortoloco Emails gebraucht werden sollte. Als Realisierung ist ein Drop-Down (html select) geplant bei dem man beim Email Versand aus einer Liste von Absender Adressen auswählen kann. Neue Email Adressen müssen noch erstelle werden, siehe #59.

**Comment by fathoma** [comment]
Funktioniert vorerst nur, wenn die Mails über die Funktion "Locos filtern" versendet werden. Siehe auch #60.

**Comment by olmaga** [comment]
done
