### ISSUE TITLE
Vereinheitlichen der verschiedenen Möglichkeiten zum Versand von Emails an Locos

### ISSUE THREAD

**Issue by fathoma** [ortoloco/ortoloco#60]
Als Admin gibt es 4 verschieden Wege um Emails an die Locos zu schicken:

![mail_problem](https://cloud.githubusercontent.com/assets/10981921/8398785/21e5a394-1dfd-11e5-8dda-219499f54827.png)

Jede Variante wird im Code anders behandelt. Das ist ziemlich mühsam um Änderungen zu machen. Ausserdem ist es aus Benutzersicht sehr wahrscheinlich verwirrend 4 verschiedene Wege zu haben.

Ich würde vorschlagen dies unter einem Menüpunkt zu vereinen, das genaue Konzept muss ich mir noch überlegen. Kommentare/Vorschläge sind sehr willkommen :)

**Comment by olmaga** [comment]
ist jetzt ein bisschen besser
