### ISSUE TITLE
Anteilscheine-Anzahl gleich 0 im Benutzerprofil

### ISSUE THREAD

**Issue by rbf** [ortoloco/ortoloco#61]
Ich habe grade gesehen, dass bei mir (auf meinem Profil in my.ortoloco.ch) steht, dass ich 0 (d.h. keine) Anteilscheine besitze, was nicht der Fall ist.
Ist bei allen so?

**Comment by olmaga** [comment]
Jap bei allen

**Comment by schlangen** [comment]
Hi Robert,in der Ta‎t; es liegt daran, daß die Funktion noch nicht implementiert ist. Ich bin ja gerade dran, die Tabelle der UserInnen und Anteilscheine zusammenzubringen.Auf der Grundlage muessen wir dann das Feature basteln.LG, Dirk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: rbfSent: Friday, 17 July 2015 19:31To: ortoloco/ortolocoReply To: ortoloco/ortolocoSubject: [ortoloco] Anteilscheine-Anzahl gleich 0 im Benutzerprofil (#61)Ich habe grade gesehen, dass bei mir (auf meinem Profil in my.ortoloco.ch) steht, dass ich 0 (d.h. keine) Anteilscheine besitze, was nicht der Fall ist.
Ist bei allen so?

—Reply to this email directly or view it on GitHub.

**Comment by motu55** [comment]
Duplikat von https://github.com/ortoloco/ortoloco/issues/14
