### ISSUE TITLE
Als User in my.ortoloco soll eigenständiges Wechseln der Depots nicht mehr möglich sein

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#62]
Bisher konnten alle ihr Depot selbstständig wechseln. Jedoch bekommt niemand die Info, wenn ein Wechsel vorgenommen wurde (Übersicht wird so schwierig) und die Abonnentinnen bekommen auch die Infos zum neuen Depot nicht automatisch zugeschickt. Darum soll die Funktion deaktiviert werden und durch einen Text ersetzt werden: Du bist umgezogen oder möchtest aus einem anderen Grund dein Gemüse in einem anderen Quartierdepot abholen? Du kannst das Depot jederzeit wechseln - schreibe eine Mail an info@ortoloco.ch, wo du in Zukunft deine Gemüsetasche abholen möchtest.

**Comment by rbf** [comment]
@motu55 Merci fürs fleissige Coden! :+1:

Wegen Issue-Schliessen sollen wir uns etwas ausdenken, weil so bekommt die BG nicht deutlich mit, dass es implementiert wurde, und überhaupt ob die Implementierung erfüllt, was nötig war.

Wie wäre es, wenn wir den Issue nur als `Ready to validate` markieren, und ein Kommentar im Issue-Thread (diese Seite) einfügen, so das die Person, die das Issue geöffnet hat, es überprüfen kann sobald es released ist. Dann kann diese Person den Issue schliessen?

Was meint ihr?

@olmaga ?

**Comment by tinaortoloco** [comment]
Danke Robert, für diesen Input.
Zwar bekomme ich als erlauchtes Mitglied der Github-Community auch  
mit, wenn etwas gelaufen ist bei den Issues, jedoch weiss ich dann  
jeweils nicht genau, was und wie. Daher macht dein Vorschlag sehr Sinn.

LG Tina


Zitat von rbf <notifications@github.com>:
