### ISSUE TITLE
Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by rbf** [ortoloco/ortoloco#64]
http://www.ortoloco.ch/photologue/gallery/page/1/

Wahrscheinlich nach der Migration nach heroku...?

**Comment by zoliv** [comment]
und

my.ortoloco.ch  <http://my.ortoloco.ch>   funktioniert nicht...

bleibt im gleiche Seite wie ortoloco.ch

( nur wan man auf der unteren recht link mit  class="myortoloco_link"
clickt geht es )

War das immer so?

(sorry bin grade nicht im github fur ein neue Issue)


Zé Oliveira

www.zeoliveira.com

Tel: 0041 (0)77 421 54 78

José Duarte de Oliveira
Austrasse 50
8953 Dietikon
Schweiz

**Comment by rbf** [comment]
Yep, nach der Umstellung nach heroku ist es so.

@olmaga
Eigentlich konnte man `my.ortoloco.ch` auf `www.ortoloco.ch/my` weiterleiten, oder?

**Comment by olmaga** [comment]
längst gflickt
