### ISSUE TITLE
Absenderadresse in Info-E-Mails ist nicht richtig

### ISSUE THREAD

**Issue by rbf** [ortoloco/ortoloco#68]
Ich habe gerade eine Info-E-Mail bekommen, und die Absenderadresse ist nicht richtig (siehe Bild).

![screen shot 2015-10-10 at 19 40 54](https://cloud.githubusercontent.com/assets/807084/10412461/f25bc802-6f86-11e5-8ab1-3dcfa72c5c3b.png)

**Comment by tinaortoloco** [comment]
Lieber Robert

Danke für die Mail.

Eigentlich ist die Absenderadresse schon richtig, die Mail mit allen  
offenen Jobs wird von mir verschickt und ich bin froh, wenn die  
Reaktionen darauf auf info@ kommen. Oder verstehe ich da etwas falsch?  
Merci fürs Aufklären. :-)

LG Tina


Zitat von rbf <notifications@github.com>:

**Comment by schlangen** [comment]
Hi Tina,

ich glaube es ging Robert um Folgendes:

![mail_sender_issue](https://cloud.githubusercontent.com/assets/7895715/10426667/95fc5844-70e2-11e5-8f4a-f92bd13ec6b1.png)

Offenbar wird an den Absender (info@ortoloco.ch") noch dieser Zusatz angehägt (" '@ortoloco"). Das resultiert bestimmt aus einer e-mail Funktion, die ansonsten vor das '@ortoloco) noch den "wahren" Absender / diee "wahre" Absenderin setzt; was praktisch wäre, wenn bestimmte "Einzeladressen" eingesetzt werden sollen.

Sollte eigentlich nicht so schwer zu korrigieren sein.

Dirk

**Comment by olmaga** [comment]
fixed
