### ISSUE TITLE
Jobs mit "Freien Plätzen" gleich Null ergeben ZeroDivisionError (error 500) auf /my/home

### ISSUE THREAD

**Issue by rbf** [ortoloco/ortoloco#70]
Kürzlich wurde ein Job mit "Freien Plätzen" gleich Null auf `/admin` und das hat zu einem `ZeroDivisionError` Fehler geführt. Siehe unten für Details.

Punkte zu behandeln:

- [ ] Fehler im [`my_ortoloco/models.py`](https://github.com/ortoloco/ortoloco/blob/master/my_ortoloco/models.py#L364) vermeiden.
- [ ] Überlegen, wie man deutlich Vermitteln kann, dass ein Job abgesagt wurde (das war der Grund einen Job ohne freie Plätze zu erstellen):

![screen shot 2015-11-17 at 09 09 59](https://cloud.githubusercontent.com/assets/807084/11205855/4c56acd6-8d0b-11e5-9157-7519063664eb.png)

```
Request Method:	GET
Request URL:	http://www.ortoloco.ch/my/home
Django Version:	1.6
Exception Type:	ZeroDivisionError
Exception Value:	
integer division or modulo by zero
Exception Location:	/app/my_ortoloco/models.py in get_status_bohne, line 364
```

```
Error during template rendering

In template /app/my_ortoloco/templates/myhome.html, error at line 19
integer division or modulo by zero
9	
10	    {% autoescape off %}
11	        {{ announcement }}
12	    {% endautoescape %}
13	    <h3>Aktuelle Arbeitseinsätze</h3>
14	    <table class="jobs">
15	        {% for job in jobs %}
16	            <tr class="{% if job.status == "erbse_voll.png" %}full{% endif %}">
17	                <td class="date">{{ job.time |date:"d.m H:i" }}</td>
18	                <td><a href="/my/jobs/{{ job.id }}">{{ job.typ.name }}</a></td>
19	                <td class="status"><img alt="Job-Status: {{ job.get_status_bohne }}" src="/static/img/{{ job.get_status_bohne }}"/></td>
20	            </tr>
21	        {% endfor %}
22	    </table>
23	    <br/>
24	    <a href="/my/einsaetze">Hier alle Arbeitseinsätze anzeigen</a>
25	    <br/><br/><br/>
26	    <h4>Zu den Kalendern der einzelnen Tätigkeitsbereiche</h4>
27	    <table class="teams">
28	        {% for team in teams %}
29	            <tr>
```

**Comment by rbf** [comment]
To: @tinaortoloco @christianloco 
CC: @olmaga 

Könnt ihr bitte die Person, die diesen Job (#1612) erstellt hat, informieren, dass es gelöscht wurden? Ich kann nicht wissen, wer das war.

Wie in diesem Issue angegeben, Jobs mit "Freien Plätzen" gleich Null ergeben ein Fehler auf my.ortoloco, so dass die Webseite nicht benutzbar ist. Bitte bis wir eine besseren Lösung finden, Job-Absagen per E-Mail melden!

Danke!

**Comment by motu55** [comment]
fixed the 0 issue and added a possibility to cancel jobs when editing them and that it is displayed properly on the webpage. at least in the job and jobs page
@rbf  am I correct in the assumption that jobs are created under the console /admin and not in a special form which is on my ortoloco? and this admin thing is a standard django thing?

**Comment by rbf** [comment]
Can you please share a screenshot of the resulting implementation to better understand what you mean?

> @rbf am I correct in the assumption that jobs are created under the console /admin and not in a special form which is on my ortoloco? and this admin thing is a standard django thing?

2 x yep

**Comment by tinaortoloco** [comment]
Liebe Leute

Danke für den Hinweis, dass man keinen Job mit "freie Plätze = 0"  
erstellen kann. Wir wollten so auf einen abgesagten Aktionstag  
aufmerksam machen und verhindern, dass sich da noch jemand eintragen  
kann. Aber dann machen wir das in Zukunft bei ähnlichen Fällen einfach  
so, dass wir einen Platz ausschreiben und den gleich selber besetzen.

Liebe Grüsse
Tina


Zitat von rbf <notifications@github.com>:
