### ISSUE TITLE
Als User in my.ortoloco erscheint Error beim Klick auf den Button "Kontakt" unter Abo --> Depots

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#71]
Wenn einE ortoloc@ das Depot ändern will, muss sie/er per Kontakt-Button eine Nachricht an info@ortoloco schicken (my.ortoloco.ch --> Abo --> Depot).
Leider erscheint eine Error-Meldung, wenn auf diesen Knopf drückt.

**Comment by motu55** [comment]
fixed and ready for deploy  @tinaortoloco please close after retest
