### ISSUE TITLE
Auf statischer Homepage unter Anmeldefenster für politiloco die Twitter-Adresse einfügen

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#73]
Unter http://www.ortoloco.ch/kontakt gibt es unten auf der Seite die Möglichkeit, sich für den politoloco-Newsletter anzumelden. Dort bitte die Twitter-Adresse https://twitter.com/PolitolocoZueri ergänzen.

**Comment by motu55** [comment]
@tinaortoloco 
kannst du bitte genaue spezifizieren wie das ausehen soll. am besten Text hier reinkopieren wie er nacher aussehen sollte
thx

**Comment by olmaga** [comment]
Done
