### ISSUE TITLE
Wechsel Anfang Jahr von Warteliste zu aktiven Abos: automatisch oder manuell?

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#74]
Kein klassisches Issue, trotzdem platziere ich das hier:
Muss der Wechsel einerseits der neuen Gnossis, die auf der Warteliste sind und andererseits der Gnossis, die das Abo gekündet haben, manuell erfolgen? Oder gibt es hier die Möglichkeit, zu automatisieren?

**Comment by olmaga** [comment]
http://www.ortoloco.ch/my/zukunft
