### ISSUE TITLE
Mail-Funktion in my.ortoloco bei "nur an diese Mail verschicken" geht nicht richtig

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#76]
Es gibt einen Fehler, wenn ich auf my.ortoloco auf "mails verschicken" gehe und "nur an diese Mail schicken" anklicke. Wenn ich in dieses Feld mehrere Mailadressen reinkopiere (z.B. aus locos filtern), dann wird das Mail jeweils nur an den ersten verschickt. Es sollte aber möglich sein, an mehrere gleichzeitig zu verschicken.

**Comment by motu55** [comment]
@tinaortoloco 
implemented can be tested with next golive please close when retested
