### ISSUE TITLE
Als Admin die Möglichkeit haben, einmalige Jobs ohne Jobart auszuschreiben

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#77]
Einige Jobs sind nur einmal im Jahr, z.B. Sauerkraut machen oder Zuckerhut ernten. Auch für diese Jobs muss man aber zuerst eine Jobart erstellen, vor allem wenn man in der Beschreibung etwas drinhaben möchte, das sonst nirgends anderswo vorkommt. Das führt zu einer Unübersichtlichkeit bei den Jobarten. Löschen geht auch nicht, da man ja so die Böhnlis mitlöschen würde.
Es wäre super, wenn es die Möglichkeit gäbe, Jobs nur einmalig auszuschreiben ohne eine Jobart erstellen zu müssen.

**Comment by tinaortoloco** [comment]
Kann mir noch jemand kurz erklären, ob und wie das neue Feature funktioniert? Merci! :-)

**Comment by motu55** [comment]
1. Es geht
2. tex weiss wie
Es gibt jetzt neu im admin bereich wo man die jobs erstellt einen neuen typ einzeljob wo man einzelne jobs erstellen kann.

unter jobart kann man nun aufrämene in dem man die jobarten auswählt welche für solche einzeljobs erstellt wurden. Also auswählen mit häckchen setzen links dan ganz nach oben scrollen und dann bei dem drop down auswählen jobart in einzeljobs konvertieren. so bleiben böhnli und andere infos erhalten
