### ISSUE TITLE
zwei kleine Änderungen bei den Depotlisten

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#78]
a) Wenn 2 Blätter pro Depot anfallen, dann die Zeile mit den Angaben zu Anzahl Taschen/ Eiern/ Käse/ Früchte etc. nochmals mit auf das zweite Blatt aufnehmen 
b) Die Reihenfolge der Anzahl grosse und kleine Zusatzabos, etc. ist vermutlich nicht bei jedem Depot immer gleich, es wäre hilfreich alles zu standardisieren.

**Comment by olmaga** [comment]
done
