### ISSUE TITLE
Als User: Anzeige der nächsten eigenen Einsätze chronologisch

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#79]
Anscheinend werden die Einsätze auf dem my.ortoloco-Account in der Reihenfolgen angezeigt, wie man sich eingetragen hat, und nicht chronologisch. D.h. wenn ich mich für den Aktionstag am nächsten Samstag eintrage und später mich dann aber noch fürs Ernten am Montag vorher, dann wird trotzdem zuerst der Aktionstag und dann erst das Ernten angezeigt.
Es wäre hilfreich, wenn die Einsätze, in die man sich eingetragen hat, chronologisch angezeigt würden.

**Comment by motu55** [comment]
@tinaortoloco 
habe das probiert zu reproduzieren und alle wurden richtig geordnet. das kann ich auch so im code sehen seit Dec 2013 ist das so. bite entweder einen screenshot anhängen falls man das irgendow gerade sieht ansonsten kann man das hier zumachen.
