### ISSUE TITLE
History sichtbar machen oder Datum anzeigen bei Änderungen

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#80]
Es wäre super, wenn jeweils das Datum sichtbar wäre, wann sich jemand als neueR Gnossi angemeldet hat, resp. wenn die History sichtbar wäre. Wenn das geht, wäre es allgemein gut, wenn alle Änderungen, die vorgenommen werden, datiert werden oder die History sichtbar wäre.

**Comment by motu55** [comment]
Mit der neuen Django Version gibt es wenn man im admin Bereich einen Loco oder sonst was anschaut oben rechts einen Geschichte Button der genau das anzeigt. Ich habe Für locos und Abos einträge hinzugefügt wenn sie damals aus dem alten system übernommen wurden.
