### ISSUE TITLE
Admin-Bereich: Passwort ändern funktioniert nicht mehr

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#83]
Wenn ich im Admin-Bereich über "Benutzer" das Passwort ändern will, klappt das offenbar nicht. Der Vorgang scheint zwar ohne Fehlermelung zu laufen, aber wenn ich mich dann mit der entsprechenden Mailadresse und mit dem neuen Passwort bei my.ortoloco einloggen will, heisst es, dass dies kein gültiges Login sei.
Danke fürs Reparieren!

**Comment by motu55** [comment]
funktioniert wieder mit der neuen Django version
