### ISSUE TITLE
Bug!! Als Admin: Error bei Klick auf "alle Einsätze anzeigen" sowie "Kalender der Tätigkeitsbereiche" 

### ISSUE THREAD

**Issue by tinaortoloco** [ortoloco/ortoloco#86]
Im Admin-Bereich von my.ortoloco.ch erscheint beim Klick auf "Einsätze", "alle Einsätze anzeigen" und "Kalender der Tätigkeitsbereiche" die Meldung Server Error (500).
Wär super, wenn ihr das so schnell wie möglich anschauen und flicken könnt, die Leute können sich sonst nur in die Jobs einschreiben, die grad als aktuellste angezeigt werden. Daaankeee!

**Comment by olmaga** [comment]
soeben live geflickt

**Comment by tinaortoloco** [comment]
Danke!!!

Zitat von olmaga <notifications@github.com>:
